---
- name: Generate terraform configs using var count provided in command line
  debug: msg="Need to run with -e "counter=N" where N is a number of Consul hosts"

  
- template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
  - { template: "ec2.j2.template.tf" , dest: "/home/git/devopsstuff/ec2_instances.tf" }
  - { template: "assume_role_policy.j2.json" , dest: "/home/git/devopsstuff/assume_role_policy.json" }
  - { template: "consul_policy.j2.json"  , dest: "/home/git/devopsstuff/consul_policy.json" }
  tags:
  - terra_configs