---
- name: Generate terraform configs using var count provided in command line
  debug: msg="Need to run with -e "counter=N" where N is a number of Consul hosts"

  
- template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
  - { template: "ec2.j2.template.tf" , dest: "/home/git/devopsstuff/ec2_instances.tf" }
# - { template: "vpc.j2.template.tf" , dest: "/home/git/devopsstuff/vpc.tf" }
  tags:
  - terra_configs