---
# tasks file for install_consul

- name: Install consul 
  include: install_consul.yml
  become: yes
  tags:
    - consul
    
- name: Create ssl certs and CA using openssl
  include: ssl.yml  
  become: yes
  tags:
    - openssl
    
- name: Create ssl certs using using consul binary
  include: consul_ssl.yml  
  become: yes
  tags:
    - consul_ssl
