---
- name: Download Terraform binary
  become: yes
  unarchive:
    src:  "https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
    remote_src: yes
    dest: /bin/   
    owner: root
    group: root
    mode: '0755'
